[package]
name = "c_codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.98", default-features = false, features = ["std"] }
pretty = { version = "0.12.3", default-features = false }
thiserror = { version = "2.0.3", default-features = false, features = ["std"] }
